---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-grafana-sa
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-contour
  interval: 4m0s
  path: ./grafana-sa
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
    namespace: tanzu-continuousdelivery-resources


