apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tanzu-packages-namespaces.yaml
- tanzu-packages-cert-manager-sa.yaml
- tanzu-packages-contour-sa.yaml
- tanzu-packages-fluent-bit-sa.yaml
- tanzu-packages-grafana-sa.yaml
- tanzu-packages-harbor-sa.yaml
- tanzu-packages-prometheus-sa.yaml