apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tanzu-packages-cert-manager.yaml
- tanzu-packages-contour.yaml
- tanzu-packages-fluent-bit.yaml
- tanzu-packages-grafana.yaml
- tanzu-packages-harbor.yaml
- tanzu-packages-prometheus.yaml

