apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- grafana-package-install.yaml
secretGenerator:
- name: grafana-packages-values
  namespace: packages
  files:
  - grafana-data-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: grafana-packages