apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- fluent-bit-package-install.yaml
secretGenerator:
- name: fluent-bit-packages-values
  namespace: packages
  files:
  - fluent-bit-data-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: fluent-bit-packages