apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: '6.0.1'
      sourceRef:
        kind: bitnami/wordpress
        name: tmm-wordpress
        namespace: default
      interval: 1m
  values:
    replicaCount: 2
    wordpressUsername: admin
    wordpressPassword: "SecurePass1!"
    mariadb.auth.rootPassword: "SecurePass1!"
